### PR TITLE
Disable GL_EXT_texture_array on OpenGL ES 2.0

### LINKED ISSUE #1647: Bug in Nvidia Tegra 3 driver
I'm trying to run LÖVE on an Ouya, which has an Nvidia Tegra 3. It supports OpenGL ES 2.0, which [doesn't support 3D textures](http://docs.gl/es3/glTexImage3D#versions). It also doesn't support the [ES 2.0 extension for 3D textures](https://www.khronos.org/registry/OpenGL/extensions/OES/OES_texture_3D.txt).

Currently, LÖVE checks to see if the extension is supported, and if it is, it aliases the functions for easier use later:

https://github.com/love2d/love/blob/0b06d0d1f9defaef0353523012acf918cbc01954/src/modules/graphics/opengl/OpenGL.cpp#L394-L403

On my Ouya, is doesn't matter whether these functions get alias or not, because both the regular versions and the OES versions are NULL.

As a result, I get a segfault during the boot process when LÖVE uses a 3D texture function for the first time:

```
<unknown> 0x0000000000000000
glad::glTexImage3D(unsigned int, int, int, int, int, int, int, unsigned int, unsigned int, void const*) gladfuncs.hpp:376
love::graphics::opengl::OpenGL::rawTexStorage(love::graphics::TextureType, int, love::PixelFormat, bool&, int, int, int) OpenGL.cpp:1171
love::graphics::opengl::OpenGL::createDefaultTexture() OpenGL.cpp:533
love::graphics::opengl::OpenGL::setupContext() OpenGL.cpp:261
love::graphics::opengl::Graphics::setMode(int, int, int, int, bool) Graphics.cpp:167
love::window::sdl::Window::setWindow(int, int, love::window::WindowSettings*) Window.cpp:527
love::window::w_setMode(lua_State*)::$_2::operator()() const wrap_Window.cpp:119
int love::luax_catchexcept<love::window::w_setMode(lua_State*)::$_2>(lua_State*, love::window::w_setMode(lua_State*)::$_2 const&) runtime.h:663
love::window::w_setMode(lua_State*) wrap_Window.cpp:118
lj_BC_FUNCC 0x0000000068df1ed0
love::luax_resume(lua_State*, int) runtime.cpp:971
runlove(int, char**, int&) love.cpp:218
::SDL_main(int, char **) love.cpp:259
Java_org_libsdl_app_SDLActivity_nativeRunMain SDL_android.c:761
dvmPlatformInvoke 0x0000000040749e34
dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) 0x0000000040778dce
dvmJitToInterpNoChain 0x00000000407532a8
```

If I comment out that line I get this segfault:

```
<unknown> 0x0000000000000000
glad::glTexSubImage3D(unsigned int, int, int, int, int, int, int, int, unsigned int, unsigned int, void const*) gladfuncs.hpp:377
love::graphics::opengl::OpenGL::createDefaultTexture() OpenGL.cpp:549
love::graphics::opengl::OpenGL::setupContext() OpenGL.cpp:261
love::graphics::opengl::Graphics::setMode(int, int, int, int, bool) Graphics.cpp:167
love::window::sdl::Window::setWindow(int, int, love::window::WindowSettings*) Window.cpp:527
love::window::w_setMode(lua_State*)::$_2::operator()() const wrap_Window.cpp:119
int love::luax_catchexcept<love::window::w_setMode(lua_State*)::$_2>(lua_State*, love::window::w_setMode(lua_State*)::$_2 const&) runtime.h:663
love::window::w_setMode(lua_State*) wrap_Window.cpp:118
lj_BC_FUNCC 0x0000000068df1db0
love::luax_resume(lua_State*, int) runtime.cpp:971
runlove(int, char**, int&) love.cpp:218
::SDL_main(int, char **) love.cpp:259
Java_org_libsdl_app_SDLActivity_nativeRunMain SDL_android.c:761
dvmPlatformInvoke 0x0000000040749e34
dvmCallJNIMethod(unsigned int const*, JValue*, Method const*, Thread*) 0x0000000040778dce
dvmJitToInterpNoChain 0x00000000407532a8
```

And finally, if I also comment out that line, I don't get a segfault, but LÖVE successfully catches the following fatal error:

```
Error: [string "boot.lua"]:535: Cannot compile vertex shader code:
    (104) : error C1115: unable to find compatible overloaded function "texture2DArray(sampler2DArray, vec3)"
    
    stack traceback:
    	[string "boot.lua"]:777: in function <[string "boot.lua"]:773>
    	[C]: in function 'setMode'
    	[string "boot.lua"]:535: in function <[string "boot.lua"]:380>
    	[C]: in function 'xpcall'
    	[string "boot.lua"]:787: in function <[string "boot.lua"]:780>
    	[C]: in function 'xpcall'
```

### PR DESCRIPTION
**Pull request by xordspar0**
The Nvidia Tegra 3 driver for Android (used by Ouya) erroneously claims
to support the desktop-oriented GL_EXT_texture_array extension. On
desktop GPUs using (non ES) OpenGL, the glTexImage3D and similar
functions are always present, and the GL_EXT_texture_array extension
simply adds support for texture arrays to those functions. On OpenGL ES
2.0, those functions do not exist, and GL_OES_texture_3D is required to
define them.

Calling glTexImage3D on the Tegra 3 causes a segfault. This change works
around the issue by manually setting GLAD_EXT_texture_array to 0 on
OpenGL ES 2.0 systems, which causes LÖVE to avoid codepaths that assume
that the 3D texture functions are available. It doesn't make sense for
any OpenGL ES 2.0 GPU to claim support for GL_EXT_texture_array.

Fixes #1647

### CODE REVIEW

File: src/modules/graphics/opengl/OpenGL.cpp [hunk 1]
```diff
@@ -391,15 +391,23 @@ void OpenGL::initOpenGLFunctions()
...
-		//fp_glTexImage3D = fp_glTexImage3DOES;
-		fp_glTexSubImage3D = fp_glTexSubImage3DOES;
-		fp_glCopyTexSubImage3D = fp_glCopyTexSubImage3DOES;
-		fp_glCompressedTexImage3D = fp_glCompressedTexImage3DOES;
-		fp_glCompressedTexSubImage3D = fp_glCompressedTexSubImage3DOES;
-		fp_glFramebufferTexture3D = fp_glFramebufferTexture3DOES;
+		// The Nvidia Tegra 3 driver (used by Ouya) claims to support GL_EXT_texture_array but
+		// segfaults if you actually try to use it. OpenGL ES 2.0 devices should use OES_texture_3D.
+		// GL_EXT_texture_array is for desktops.
+		GLAD_EXT_texture_array = false;
```
Comment (xordspar0) [inline src/modules/graphics/opengl/OpenGL.cpp:399]: I put this here because I thought it made sense to keep it near the other OpenGL ES 2.0 texture code, however, there is a check above on line 352 that uses GLAD_EXT_texture_array:

		if (GLAD_VERSION_1_0 && GLAD_EXT_texture_array)
			fp_glFramebufferTextureLayer = fp_glFramebufferTextureLayerEXT;

This doesn't cause any problems today, but maybe it's still better to be safe and add the new code closer to the top of the function.

File: src/modules/graphics/wrap_GraphicsShader.lua [hunk 2]
```diff
@@ -54,7 +54,8 @@ GLSL.SYNTAX = [[
 	#define DepthCubeImage samplerCubeShadow
 #endif
 #define extern uniform
-#ifdef GL_EXT_texture_array
+#if defined(GL_EXT_texture_array) && (!defined(GL_ES) || __VERSION__ > 100)
+#define texture_arrays_enabled
```
Comment (xordspar0) [inline src/modules/graphics/wrap_GraphicsShader.lua:58]: I am not sure how correct this is. `(!defined(GL_ES) || __VERSION__ > 100)` is my attempt to say "if we're on OpenGL ES 2.0". It works on my Ouya, but I'm not sure if it does what I want elsewhere.

I'm also not sure if the `#define texture_arrays_enabled` style is a good idea.

Feedback is welcome.

Comment (slime73) [reply src/modules/graphics/wrap_GraphicsShader.lua:58]: This will need some tweaks to work with how LÖVE does things with OpenGL ES, but the reasoning and changes needed are so obscure that I think I'll just merge this as-is and make the changes after.

Comment (xordspar0) [reply src/modules/graphics/wrap_GraphicsShader.lua:58]: Thanks!
